### ISSUE TITLE
misc:cursor_zoom_factor was renamed to cursor:zoom_factor

### ISSUE THREAD

**Issue by markfswe** [M1cha/hyprctl-custom#4]
simply changing name of property doesn't work for me.. getting `Error: SerdeError(Error("expected ident", line: 1, column: 2))`

**Comment by M1cha** [comment]
Version 0.3 of the crate `hyprland` became incompatible with current versions of hyprland which caused other commands to break as well. I fixed that and renamed the cursor zoom keyword. Please test if version [0.3.0](https://github.com/M1cha/hyprctl-custom/releases/tag/v0.3.0) of hyprctl-custom works for you.

**Comment by ekhodx** [comment]
Nice! Works great. Thank you for fast response

---

I really don't want to install pyprland with all it's bloat for only this feature :sob: 
https://hyprland-community.github.io/pyprland/magnify.html
